# Site settings
title: Prabhu Cheedalla
description: 
url: 'https://explorer9.github.io/'
baseurl: '/wiz'
profilepic: '/images/prabhu.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Prabhu chaitanya cheedalla'
  email: cheedallaprabhu@gmail.com
  twitter_username: 
#  facebook_username: joshgerdes
  github_username:  explorer9
  linkedin_username:  Prabhu Cheedalla
  #meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']

theme: jekyll-theme-cayman
