# Site settings
title: Sreeharsha Bandi
description: 'Business Card Page'
url: 'https://bac2binary.github.io'
baseurl: '/wiz/'
profilepic: '/images/harsha.png'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Sreeharsha Bandi'
  email: bandi5398@gmail.com
  twitter_username: 0xHarsha
#  facebook_username: joshgerdes
  github_username:  bac2binary
  linkedin_username:  bandi-sreeharsha
  #meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']

theme: jekyll-theme-cayman
